### ISSUE TITLE
Some time random-string function is not generating the string based on the provided combination

### ISSUE THREAD

**Issue by gowrishyadalam** [valiton/node-random-string#7]
I have using this plugin to generate the password, but some times it not generating the string based on the provided combination

Here is my use case 

newPassword = randomString({ length: 18, numeric: true, letters: true, special: true })

observed behavior:
In my scenario it is genrating the random string of length 18 without integers

expected behavior:
 It should generate the random string of length 18 with integers, aplhabets and special charecters

my random-string package version is '0.2.0'

help me on this

**Comment by hereandnow** [comment]
the generated string is **really random**. there is **no guarantee** that at least one of the specified characters is included. a short look at the existing source code could have saved you the time to open up this issue ;-) 

a feature like that would mean probably another config-option and additonal implementation/rewrite. pull request is welcome
